### PR TITLE
Blog Update : 2015-06-26

### PR DESCRIPTION
**Pull request by amitjamadagni**
Updates from the recent weeks : Week 3, 4, 5.

### CODE REVIEW

**Comment by acroy** [comment]
@amitjamadagni : I also think this looks good. Could you address the point raised by Qi?

**Comment by amitjamadagni** [comment]
@acroy  @i2000s  done !

**Comment by amitjamadagni** [comment]
@acroy updated the type hierarchy.

**Comment by acroy** [comment]
Sorry for the delay!

**Pull request merged**
